### ISSUE TITLE
How to built vocabulary ?

### ISSUE THREAD

**Issue by shubhamsaini** [wihoho/Image-Recognition#3]
Hi,

I am trying to build vocabulary for my own data set. I am not sure what to give into 'stackOfDescriptors' to the visualVocabulary class.

Any help?

**Comment by wihoho** [comment]
You can get it from the following method in utils.py 

def readImages(folderPath):

**Comment by shubhamsaini** [comment]
It wouldn't work for me.

```
>>> trainData = utils.readImages(path)
>>> voc = Vocabulary(trainData,10)
```

gives me this error:

```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "recognition/visualVocabulary.py", line 13, in __init__
    kmeans.fit(stackOfDescriptors)
  File "//anaconda/lib/python2.7/site-packages/sklearn/cluster/k_means_.py", line 1235, in fit
    X = check_array(X, accept_sparse="csr", order='C', dtype=np.float64)
  File "//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py", line 373, in check_array
    array = np.array(array, dtype=dtype, order=order, copy=copy)
AttributeError: imageDescriptors instance has no attribute '__float__'
```

**Comment by wihoho** [comment]
You need to modify the 
def readImages(folderPath):

to let it return stackOfDescriptors

**Comment by shubhamsaini** [comment]
Oh, you mean the stackOfFeatures = [] variable within the readImages function?

Each image is approximately (9x128) features. So with 1000 images I am getting an array of (9000x128) array as stackOfFeatures which does not seem right.

**Comment by wihoho** [comment]
Did you try?

 (9000x128) is right. Please catch up more on machine learning.
